# Xavier Bresson

name: deeplearn_course


channels:
  
  - pytorch # DL
  - https://conda.anaconda.org/rdkit # Molecule
  - dglteam # DGL
  - conda-forge # RL/numpy/scipy
  - pytorch-lts # torchvision

dependencies:

  # basic
  - python=3.7.10
  - numpy=1.21.1
  - mkl=2021.3.0
  - ipython=7.26.0
  - jupyter=1.0.0
  - scipy=1.7.1
  - pandas=1.3.1
  - matplotlib=3.4.2
  - scikit-learn=0.24.2
  - networkx=2.6.2
  - seaborn=0.11.1 

  - pytorch=1.9.0 # DL
  - torchvision=0.10.0 # CV 
  - rdkit=2020.09.1.0 # Molecule
  - dgl=0.7.0 # DGL

  - pip:
    - gym==0.18.0 # RL
    - tensorboardx==2.2 # TSP
    - fastprogress==1.0.0 # TSP